### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by yegle** [aumayr/fava#247] opened 2016-04-02 23:46 UTC
I was running fava in both OS X and Linux and the memory easily increase to >1GB in few days of running.

**Comment by yagebu** [comment] 2016-04-03 15:13
I don't think that we have any data structures in fava that grow indefinitely, so I don't have an idea where this is coming from if the garbage collection is doing its job. Does this also happen if you run it in debug mode?

**Comment by corani** [comment] 2016-04-07 15:33
I've added some instrumentation, to dump memory usage summaries, in my
local install and can't reproduce this issue (on Linux). After a couple of
days, I don't see significant growth in memory usage (in debug mode).

I'll try the same in normal mode, as the only candidate I can think of
would be something related with the auto-reloader.

**Comment by yegle** [comment] 2016-04-07 16:46
@corani that's my suspicion as well. I'm using fava to check a Dropbox directory, of which I frequently add new documents and modify them.

**Comment by corani** [comment] 2016-04-07 17:00
May be related to #250

**Comment by corani** [comment] 2016-04-13 09:29
While I haven't figured out where the leak is happening, it does appear to be real.

Here's what I observed:

**Initial memory usage**
```
refs:
7674	<class 'list'> [['module(encodings.utf_8)', 1, 80], ['function (_close)', 3, 408], ['function (with_hostmask)', 3, 
3234	<class 'list'> [Price(meta={'lineno': 1, 'filename': 'prices.bean'}, date=datetime.date(2000
1698	<class 'dict'> {9125888: <weakref at 0x2b14619b6b88; to 'type' at 0x8b4000 (odict_iterator)>, 8883200: <weakref at 
740	<class 'dict'> {'IO_EINPROGRESS': 1513, 'ERR_ENTITYREF_IN_DTD': 17, 'RNGP_ELEMENT_NO_CONTENT': 1020, 'IO_ENXIO': 15
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(

types:
177995	 <class 'beancount.core.data.Posting'>
114158	 <class 'beancount.core.amount.Amount'>
94660	 <class 'list'>
83573	 <class 'dict'>
80220	 <class 'beancount.core.data.Transaction'>
13863	 <class 'function'>
11512	 <class 'beancount.core.data.TxnPosting'>
6472	 <class 'beancount.core.data.Price'>
5719	 <class 'tuple'>
5484	 <class 'beancount.core.data.Open'>
```

**Add six prices**
```
[I 160413 17:20:47 handlers:92] Reload 1 waiters: prices.bean
[I 160413 17:20:51 handlers:132] Browser Connected: http://192.168.2.100:5000/balance_sheet/?interval=quarter
```

**New memory usage**
```
refs:
7675	<class 'list'> [['module(encodings.utf_8)', 1, 80], ['function (_close)', 3, 408], ['function (with_hostmask)', 3, 
3240	<class 'list'> [Price(meta={'lineno': 1, 'filename': 'prices.bean'}, date=datetime.date(2000
1698	<class 'dict'> {9125888: <weakref at 0x2b14619b6b88; to 'type' at 0x8b4000 (odict_iterator)>, 8883200: <weakref at 
740	<class 'dict'> {'IO_EINPROGRESS': 1513, 'ERR_ENTITYREF_IN_DTD': 17, 'RNGP_ELEMENT_NO_CONTENT': 1020, 'IO_ENXIO': 15
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': '2015.bean'}, date=datetime.date(

types:
183667	 <class 'beancount.core.data.Posting'>
117768	 <class 'beancount.core.amount.Amount'>
97339	 <class 'list'>
86084	 <class 'dict'>
82731	 <class 'beancount.core.data.Transaction'>
13863	 <class 'function'>
11512	 <class 'beancount.core.data.TxnPosting'>
6692	 <class 'beancount.core.data.Price'>
5719	 <class 'tuple'>
5663	 <class 'beancount.core.data.Open'>
```

**Delta**
```
                                    types |   # objects |   total size
========================================= | =========== | ============
                             <class 'dict |        2511 |    706.22 KB
                              <class 'str |       10517 |    679.07 KB
      <class 'beancount.core.data.Posting |        5672 |    531.75 KB
                  <class 'decimal.Decimal |        3610 |    366.64 KB
                             <class 'list |        2679 |    280.49 KB
  <class 'beancount.core.data.Transaction |        2511 |    274.64 KB
     <class 'beancount.core.amount.Amount |        3610 |    197.42 KB
                    <class 'datetime.date |        3144 |     98.25 KB
                              <class 'int |        2168 |     59.28 KB
        <class 'beancount.core.data.Price |         220 |     17.19 KB
                        <class 'frozenset |          77 |     16.84 KB
         <class 'beancount.core.data.Open |         179 |     15.38 KB
      <class 'beancount.core.data.Balance |         125 |     11.72 KB
        <class 'beancount.core.data.Close |          54 |      3.80 KB
          <class 'beancount.core.data.Pad |          37 |      2.89 KB
```

Note specifically how an additional 5672 new `Posting` objects are created. I haven't counted them, but that sounds like a reasonable number for the total amount of postings I have on file.

I'm guessing that when reloading the source files, a new data set is created, but there still is a reference somewhere to the old data set, causing them to not be GC'd.

**Comment by corani** [comment] 2016-04-13 09:40
After running for three days with light changes:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
daniel   28335  0.6  6.8 415468 271948 pts/29  S+   Apr10  27:40 /x/beancount-web --host 0.0.0.0 -s settings.conf /x/root.bean
```
Immediately after restarting:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
daniel   10387  4.3  1.4 188920 58964 pts/29   S+   17:33   0:03 /x/beancount-web --host 0.0.0.0 -s settings.conf /x/root.bean
```

Note the drop from 272MB to 59MB after restarting

**Comment by yagebu** [comment] 2016-04-20 14:37
I currently suspect the pickle cache to be responsible for this. If the cache file is present, running `fava.application.load_file` a hundred times on an unchanged file doesn't do anything, but if the cache file is not present, memory usage will go up drastically, so I assume the pickle writer keeps some stray references around.

Ref [beancount#123](https://bitbucket.org/blais/beancount/issues/123/option-to-disable-pickle-cache).

**Comment by yagebu** [comment] 2016-04-22 13:05
Thanks @corani for the detailed investigation! Can you try running the same "tests" with the `BEANCOUNT_DISABLE_LOAD_CACHE` environment variable set?

**Comment by corani** [comment] 2016-04-22 13:53
Sure, I'll give it a try, but it might be a couple of days.

**Comment by corani** [comment] 2016-04-24 06:26
Running with `BEANCOUNT_DISABLE_LOAD_CACHE=1` doesn't appear to make a difference:

**Initial**
```
refs:
7422	<class 'list'> [['function (_get_module_lock)', 1, 136], ['function (get_prog_name)', 1, 136], ['function (_validat
3314	<class 'list'> [Price(meta={'lineno': 1, 'filename': 'prices.bean'}, date=datetime.date(2000
1682	<class 'dict'> {9125888: <weakref at 0x2b21a2140b88; to 'type' at 0x8b4000 (odict_iterator)>, 8883200: <weakref at 
740	<class 'dict'> {'C14N_RELATIVE_NAMESPACE': 1955, 'RNGP_PAT_LIST_INTERLEAVE': 1080, 'RNGP_PAT_LIST_ELEM': 1079, 'ERR
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': 'beijing-2015.bean'}, date=datetime.date(
646	<class 'dict'> {'beancount.parser.grammar': <module 'beancount.parser.grammar' from '~/.pyenv/versions/3
627	<class 'list'> [Pad(meta={'lineno': 2, 'filename': 'beijing-2013.bean'}, date=datetime.date(
544	<class 'list'> [Open(meta={'lineno': 123, 'filename': 'beijing.bean', 'account-number': '883
544	<class 'list'> [Open(meta={'lineno': 123, 'filename': 'beijing.bean', 'account-number': '883
522	<class 'list'> [Pad(meta={'lineno': 2, 'filename': 'beijing-2012.bean'}, date=datetime.date(

types:
15035	 <class 'list'>
13644	 <class 'function'>
11580	 <class 'beancount.core.data.TxnPosting'>
8319	 <class 'dict'>
8228	 <class 'beancount.core.data.Posting'>
6445	 <class 'beancount.core.amount.Amount'>
5611	 <class 'tuple'>
5097	 <class 'beancount.core.data.Transaction'>
3212	 <class 'weakref'>
2042	 <class 'type'>
```

**After making some changes**
```
refs:
7570	<class 'list'> [['function (_get_module_lock)', 1, 136], ['function (get_prog_name)', 1, 136], ['function (_validat
3320	<class 'list'> [Price(meta={'lineno': 1, 'filename': 'prices.bean'}, date=datetime.date(2000
1698	<class 'dict'> {9125888: <weakref at 0x2b21a2140b88; to 'type' at 0x8b4000 (odict_iterator)>, 8883200: <weakref at 
740	<class 'dict'> {'C14N_RELATIVE_NAMESPACE': 1955, 'RNGP_PAT_LIST_INTERLEAVE': 1080, 'RNGP_PAT_LIST_ELEM': 1079, 'ERR
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': 'beijing-2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': 'beijing-2015.bean'}, date=datetime.date(
691	<class 'list'> [Pad(meta={'lineno': 1, 'filename': 'beijing-2015.bean'}, date=datetime.date(
649	<class 'dict'> {'beancount.parser.grammar': <module 'beancount.parser.grammar' from '~/.pyenv/versions/3
627	<class 'list'> [Pad(meta={'lineno': 2, 'filename': 'beijing-2013.bean'}, date=datetime.date(
627	<class 'list'> [Pad(meta={'lineno': 2, 'filename': 'beijing-2013.bean'}, date=datetime.date(

types:
21057	 <class 'list'>
19636	 <class 'beancount.core.data.Posting'>
13855	 <class 'function'>
13789	 <class 'beancount.core.amount.Amount'>
13468	 <class 'dict'>
11580	 <class 'beancount.core.data.TxnPosting'>
10153	 <class 'beancount.core.data.Transaction'>
5708	 <class 'tuple'>
3232	 <class 'weakref'>
2062	 <class 'type'>
```

**Delta**
```
                                    types |   # objects |   total size
========================================= | =========== | ============
                              <class 'str |       22614 |      1.47 MB
                             <class 'dict |        5149 |      1.47 MB
      <class 'beancount.core.data.Posting |       11408 |      1.04 MB
                  <class 'decimal.Decimal |        7344 |    745.88 KB
                             <class 'list |        6022 |    624.63 KB
  <class 'beancount.core.data.Transaction |        5056 |    553.00 KB
     <class 'beancount.core.amount.Amount |        7344 |    401.62 KB
                    <class 'datetime.date |        6444 |    201.38 KB
                              <class 'int |        4468 |    122.17 KB
                        <class 'frozenset |         192 |     42.00 KB
        <class 'beancount.core.data.Price |         524 |     40.94 KB
         <class 'beancount.core.data.Open |         382 |     32.83 KB
                             <class 'code |         177 |     24.93 KB
                             <class 'type |          20 |     24.84 KB
      <class 'beancount.core.data.Balance |         256 |     24.00 KB
```

**Comment by yagebu** [comment] 2016-05-08 12:41
This was a bug in beancount and should be fixed now (https://bitbucket.org/blais/beancount/issues/124/possible-memory-leak-in-the-parser), can you try this again @corani?

**Comment by corani** [comment] 2016-05-13 07:25
After a couple day's use, I see no significant memory increase. If anything, the memory use went down marginally. This looks fixed to me.

**Comment by aumayr** [comment] 2016-05-13 07:56
Thanks @corani for investigating!

**Closed by aumayr** 2016-05-13 07:56 UTC
Labels: bug
