### ISSUE TITLE
Copy balance directives is limited to 751 lines?

### ISSUE THREAD

**Issue by redstreet** [aumayr/fava#221] opened 2016-03-20 00:56 UTC
Is there a limit on the number of lines for the "copy balance directives" in the Statistics page? I'm seeing 751 lines, but the remaining don't make it through. This used to work before.

One more weird thing: the "Click to copy" in the tooltip hows up for several accounts, but does not show up for accounts towards the bottom of the table that have the same status (eg: yellow, and no-gray).

**Comment by redstreet** [comment] 2016-03-20 03:48
One more weird thing: the "Click to copy" in the tooltip hows up for several accounts, but does not show up for accounts towards the bottom of the table that have the same status (eg:  yellow, and no-gray).

**Comment by redstreet** [comment] 2016-03-20 04:30
I'm not able to reproduce this issue reliably. I'll try a few more times, and if I can't reproduce it in the next few days, I'll close this out.

**Comment by redstreet** [comment] 2016-03-20 08:24
The issue is definitely appears frequently (80% of the time). Mentioning it in case you see it while using it.

**Comment by aumayr** [comment] 2016-03-23 07:25
This seems to be due to a limitation on the `title` attribute of DOM-elements, where we copy this text from:

http://stackoverflow.com/a/29869137

I will move it to a `data-` attribute, where there should be no limit:

http://stackoverflow.com/a/26898881

**Comment by aumayr** [comment] 2016-03-23 07:41
@redstreet Can you try if b2ffc5e fixes the length-limitation-issue?

**Comment by redstreet** [comment] 2016-03-23 08:19
I keep getting npm errors for any git package it tries to install when I run `make build-js`. It doesn't seem related to changes, it happens on older commits which installed fine earlier. So it's not directly related to this thread, but since I don't know much about npm, I thought I'd ask if this makes any sense to you?

````
npm ERR! git clone git://github.com/github:globegitter/chartist-plugin-tooltip Cloning into bare repository '/home/user/.npm/_git-remotes/git-github-com-github-globegitter-chartist-plugin-tooltip-ac5c9df5'...
npm ERR! git clone git://github.com/github:globegitter/chartist-plugin-tooltip fatal: remote error: 
npm ERR! git clone git://github.com/github:globegitter/chartist-plugin-tooltip   github:globegitter/chartist-plugin-tooltip is not a valid repository name
````

**Comment by yagebu** [comment] 2016-03-23 12:59
Are you running an old version of npm by chance?

**Comment by redstreet** [comment] 2016-03-24 07:37
> Are you running an old version of npm by chance?

Yes, that was the problem, thanks!

However, b2ffc5e doesn't seem to solve the issue. If there's anything I can do to help debug, do let me know.

**Comment by aumayr** [comment] 2016-03-24 07:39
> I'm seeing 751 lines, but the remaining don't make it through.

So you have more than 751 accounts, is that correct?

**Comment by redstreet** [comment] 2016-03-24 08:07
I believe it's fewer accounts, but the total number of balance directive lines exceeds 751 because of multiple commodities in in some accounts.

**Comment by yagebu** [comment] 2016-03-24 17:48
Is this something that happens in all browsers? Can you provide a beancount file to reproduce the problem?

**Comment by redstreet** [comment] 2016-03-24 20:20
The same thing happens on Chrome and IE11, both under Windows. 805 lines are being copied currently.

I'll try to provide a beancount file, but this might be difficult as I'd have to reproduce the problem from the example file. It might be a while before I can get around to it. Though it would be nice to get to the bottom of this, this is not a big deal. Thanks for looking into it!

**Comment by aumayr** [comment] 2016-05-04 21:02
@redstreet Any chance for a test-file? 😇

**Comment by redstreet** [comment] 2016-05-04 22:01
Sure, I'll look tonight or tomorrow to see if I can produce a test file.

**Comment by redstreet** [comment] 2016-05-05 05:58
So I'm unable to produce a test file easily. The issue doesn't occur when the number of balance directives is less than 700, and still occurs when it is 1100 in version 0.2.6. However, I tried a test file with 1100 commodity lots in the same account, and that works fine (all 1100 lines are copied). So something else is causing the issue to occur, and I don't know what that is.

Since this is a pain to reproduce, you could either simply close this, and I'll reopen it if I figure out a test case I can share, or if you come up with automated tests for uptodate indication that might make it easier to reproduce. Thanks for keeping this open so far!

**Comment by aumayr** [comment] 2016-05-05 07:29
OK, thanks @redstreet! I'll close this for now, but please report back if this persists and you can come up with a test/testfile.

**Closed by aumayr** 2016-05-05 07:29 UTC
Labels: bug, waiting:external
