### ISSUE TITLE
Transaction Links aren't shown

### ISSUE THREAD

**Issue by corani** [aumayr/fava#137] opened 2016-02-18 09:33 UTC
_"Transactions can also be linked together. You may think of the link as a special kind of tag that can be used to group together a set of financially related transactions over time. "_

```
2014-02-05 * "Invoice for January" ^invoice-pepe-studios-jan14
  Income:Clients:PepeStudios           -8450.00 USD
  Assets:AccountsReceivable

2014-02-20 * "Check deposit - payment from Pepe" ^invoice-pepe-studios-jan14
  Assets:BofA:Checking                  8450.00 USD
  Assets:AccountsReceivable
```

They should probably work the same way as `tags` currently do

**Comment by aumayr** [comment] 2016-02-18 09:35
Duplicate of #110

**Comment by corani** [comment] 2016-02-18 09:36
Ah, sorry, missed that one :-)

**Closed by aumayr** 2016-02-18 09:35 UTC
Labels: duplicate
